import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App.jsx';
import '@xterm/xterm/css/xterm.css';
import '@fontsource/dm-sans/latin-400.css';
import '@fontsource/dm-sans/latin-500.css';
import '@fontsource/dm-sans/latin-600.css';
import '@fontsource/manrope/latin-600.css';
import './style.css';
createRoot(document.getElementById('root')).render(<App />);
